Baseado nesse tema: A qualidade que você acredita pode estar aqui.

A trilha de Testes e Quality Management é feita para quem enxerga a qualidade como peça-chave no desenvolvimento de software — desde a concepção até a entrega.

Venha explorar diferentes formas de pensar, praticar e evoluir a qualidade, com pessoas que estão criando novos caminhos e enfrentando os desafios reais do dia a dia.

Uma trilha para quem quer se inspirar, refletir e sair com novas ideias na bagagem.

Quais dos temas a seguir fazem mais sentido para selecionar 9 temas para a trilha de Testes e Quality Management?
Além da automação: Garantindo a qualidade do produto com testes exploratórios	Testes e Quality Management	
O que a Toyota de Sorocaba me ensinou sobre entregar software com qualidade	Testes e Quality Management	
Na trilha da Cultura da Qualidade	Testes e Quality Management	
QA em Território de Dados: Testes Práticos de Qualidade com Databricks	Testes e Quality Management	
Detecte e Corrija Desperdícios de Memória com Análise Automática de Structs	Testes e Quality Management	
Des(cobrindo) Testes: Criando Sistemas Seguros e Resilientes	Testes e Quality Management	
Unit Test Calisthenics	Testes e Quality Management	
Descomplicando Testes de Performance: Conceitos e Práticas com K6	Testes e Quality Management	
Postman e a arte da automação: garantindo qualidade em APIs	Testes e Quality Management		
Gestão de Defeitos & Extração de Métricas de Bugs com Apoio de IA	Testes e Quality Management	
Automação dos testes de acessibilidade na esteira de implantação	Testes e Quality Management	
Web3: Testes de softwares na blockchain	Testes e Quality Management	
Do Zero ao E2E: Construindo uma Cultura de Automação de Testes	Testes e Quality Management	
Gestão e Liderança em Qualidade de Software	Testes e Quality Management	
Do Caos à Qualidade: Como Reduzimos 70% dos Bugs em Produção	Testes e Quality Management	
Testes exploratórios, seu companheiro de aventuras	Testes e Quality Management	
QA em jogos	Testes e Quality Management	
A arte da refatoração: Melhorando seu código sem medo	Testes e Quality Management	
AI-Driven Testing - A era da Hiperautomação!	Testes e Quality Management	
Prazos sempre estouram? Como CFD + Teoria das Restrições resolvem atrasos e retrabalho em desenvolvimento de software	Testes e Quality Management		
Qualidade com Propósito: Estratégias Adaptativas na Vida Real	Testes e Quality Management		
Evidências: uma documentação necessária	Testes e Quality Management	
Sua API não falhou — foram os dados. Como testes de dados evitam falhas silenciosas	Testes e Quality Management	
Qualidade Escalada: Superando os desafios de transição em testes de software	Testes e Quality Management	
Da instabilidade à confiabilidade do software: O papel das métricas na estratégia de teste	Testes e Quality Management	
Faça deploys sem medo... estratégia de testes e observabilidade para aumentar sua confiança	Testes e Quality Management	